

CREATE TABLE PCS(
    PATRIMONIO INT PRIMARY KEY NOT NULL,
    S_WINDOWS VARCHAR(30) UNIQUE,
    MAC_ADDRESS VARCHAR(20) UNIQUE NOT NULL,
    S_TAG VARCHAR(20) UNIQUE,
    SERIAL_PLACA VARCHAR(100) NOT NULL
);

CREATE TABLE SALAS(
    ID INT AUTOINCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    ANDAR VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE SALA_PC (
    ID INT AUTOINCREMENT PRIMARY KEY,
    PATRIMONIO INT NOT NULL,
    SALA_ID INT NOT NULL,
    FOREIGN KEY (PATRIMONIO) REFERENCES PCS(PATRIMONIO),
    FOREIGN KEY (SALA_ID) REFERENCES SALAS(ID),
    UNIQUE(PATRIMONIO)
);

CREATE TABLE MOVIMENTACAO_PC (
    ID INT AUTOINCREMENT PRIMARY KEY,
    PATRIMONIO INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    SALA_ORIGEM INT NOT NULL,
    SALA_DESTINO INT NOT NULL,
    FOREIGN KEY (PATRIMONIO) REFERENCES PCS(PATRIMONIO),
    FOREIGN KEY (SALA_ORIGEM) REFERENCES SALAS(ID),
    FOREIGN KEY (SALA_DESTINO) REFERENCES SALAS(ID)
);


ALTER TABLE PCS
    ADD COLUMN MARCA VARCHAR(150) NOT NULL,
    ADD COLUMN MODELO VARCHAR(150) NOT NULL
;

ALTER TABLE salas DROP INDEX andar;